  sudo: required 
  services:
    - docker

  before_install:
    - docker build -t peralanivvi/docker-react -f Dockerfile.dev .
  
  script:
    - docker run peralanivvi/docker-react npm run test -- --coverage
  deploy;
    provider: elasticbeamstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-438910806517"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
       secure: "$AWS_SECRET_KEY" 
