  sudo: required 
  services:
    - docker

  before_install:
    - docker build -t peralanivvi/docker-react -f Dockerfile.dev .
  
  script:
    - docker run peralanivvi/docker-react npm run test -- --coverage 
